version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql_db
      - MONGO_URI=mongodb://mongo_db:27017/empresa
    depends_on:
      - mysql_db
      - mongo_db

  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: loja
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"